algoritmo "Comissão e Salario final"

var
salario_fixo,salario_final,valor_venda,comissao:real
inicio

escreva("Digite seu salario fixo:")
leia (salario_fixo)

escreva("Digite seu total de vendas:")
leia(valor_venda)

comissao <-(valor_venda * 0.04))

salario_final <- salario_fixo + comissao

escreva("A comissão em reais é",comissao:2:2 )
escreva("Seu salario final sera de:",salario_final:2:2)



fimalgoritmo
